spring.application.name=proyectoMicroservicios
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always
spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false
